theme: jekyll-theme-midnight
title: Welcome to Anjan's homepage!
description: Hi, my name is Anjan Maharjan. My hometown is Rochester, NY and I attended Gates Chili High School. Some of my hobbies are singing, playing videogames, tennis, and watching movies.
